/* Sharova Life OS — customer authentication and paid-access gate. */
(function(){
  const PRODUCTION_URL='https://sharova-life-os-8mdq.vercel.app';
  const OWNER_EMAIL='sharonvugutsa12@gmail.com';
  let client;
  let paymentMode='direct';
  const style=document.createElement('style');
  style.textContent=`#sharova-auth-gate{position:fixed;inset:0;z-index:99999;background:rgba(31,25,22,.97);display:flex;align-items:center;justify-content:center;padding:20px;font-family:inherit}#sharova-auth-gate *{box-sizing:border-box}.sha-card{width:min(440px,100%);background:#fffaf5;border-radius:24px;padding:30px;box-shadow:0 24px 80px rgba(0,0,0,.35);color:#29231f}.sha-brand{letter-spacing:.18em;font-size:12px;font-weight:800;margin-bottom:8px}.sha-card h1{margin:0 0 8px;font-size:30px}.sha-sub{margin:0 0 22px;color:#6d625a;line-height:1.5}.sha-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;background:#eee5de;padding:5px;border-radius:12px;margin-bottom:18px}.sha-tabs button{border:0;background:transparent;padding:10px;border-radius:9px;font-weight:700;cursor:pointer}.sha-tabs button.active{background:#fff}.sha-form{display:grid;gap:12px}.sha-form label{font-size:12px;font-weight:700}.sha-form input{width:100%;padding:13px 14px;border:1px solid #d8ccc2;border-radius:10px;background:#fff;font:inherit}.sha-primary{border:0;border-radius:10px;padding:13px 16px;background:#29231f;color:#fff;font-weight:800;cursor:pointer}.sha-primary:disabled{opacity:.6}.sha-secondary{border:1px solid #d8ccc2;border-radius:10px;padding:12px 16px;background:#fffaf5;color:#29231f;font-weight:800;cursor:pointer}.sha-link{border:0;background:none;color:#6b4f3d;font-weight:700;cursor:pointer;padding:4px}.sha-msg{min-height:20px;font-size:13px;color:#6d625a}.sha-msg.error{color:#a33}.sha-msg.ok{color:#276b42}.sha-hide{display:none!important}body.sha-locked{overflow:hidden}.sha-user{position:fixed;right:18px;top:82px;z-index:30;display:flex;gap:7px;align-items:center}.sha-user span,.sha-user button{background:#fffaf5;border:1px solid #d8ccc2;border-radius:999px;padding:8px 11px;font-size:11px}.sha-user button{cursor:pointer}.sha-note{padding:12px 14px;border-radius:12px;background:#f2e9e2;color:#5f554e;font-size:12px;line-height:1.5;margin:14px 0}.sha-price{font-size:30px;font-weight:900;margin:14px 0 2px}`;
  document.head.appendChild(style);
  const gate=document.createElement('div');gate.id='sharova-auth-gate';
  gate.innerHTML=`<div class="sha-card"><div class="sha-brand">SHAROVA LIFE OS</div><h1>Your private Life OS.</h1><p class="sha-sub">Create an account to keep your Sharova workspace private and synced across your devices.</p><div class="sha-tabs"><button id="shaSignInTab" class="active">Log in</button><button id="shaSignUpTab">Create account</button></div><form id="shaAuthForm" class="sha-form"><div id="shaNameWrap" class="sha-hide"><label>Name</label><input id="shaName" autocomplete="name" placeholder="Your name"></div><div><label>Email</label><input id="shaEmail" type="email" autocomplete="email" required placeholder="you@example.com"></div><div><label>Password</label><input id="shaPassword" type="password" minlength="8" required placeholder="At least 8 characters"></div><div id="shaConfirmWrap" class="sha-hide"><label>Confirm password</label><input id="shaConfirm" type="password" minlength="8" placeholder="Repeat your password"></div><div id="shaMsg" class="sha-msg"></div><button id="shaSubmit" class="sha-primary" type="submit">Log in</button><button id="shaForgot" class="sha-link" type="button">Forgot password?</button><button id="shaResend" class="sha-link sha-hide" type="button">Resend verification email</button></form></div>`;
  document.body.appendChild(gate);document.body.classList.add('sha-locked');
  const msg=(t,c='')=>{const e=document.getElementById('shaMsg');if(e){e.textContent=t;e.className='sha-msg '+c}};
  const showResend=show=>{const e=document.getElementById('shaResend');if(e)e.classList.toggle('sha-hide',!show)};
  const setMode=signup=>{document.getElementById('shaSignInTab').classList.toggle('active',!signup);document.getElementById('shaSignUpTab').classList.toggle('active',signup);document.getElementById('shaNameWrap').classList.toggle('sha-hide',!signup);document.getElementById('shaConfirmWrap').classList.toggle('sha-hide',!signup);document.getElementById('shaForgot').classList.toggle('sha-hide',signup);showResend(false);document.getElementById('shaSubmit').textContent=signup?'Create my account':'Log in';msg('')};
  document.getElementById('shaSignInTab').onclick=()=>setMode(false);document.getElementById('shaSignUpTab').onclick=()=>setMode(true);
  const isOwner=u=>String(u?.email||'').toLowerCase()===OWNER_EMAIL.toLowerCase();
  async function active(u){const {data,error}=await client.from('user_entitlements').select('status,expires_at').eq('user_id',u.id).maybeSingle();if(error){msg('We could not verify your access. Please try again.','error');return false}return !!data&&data.status==='active'&&(!data.expires_at||new Date(data.expires_at).getTime()>Date.now())}
  async function checkout(){const b=document.getElementById('shaBuy');if(b)b.disabled=true;msg('Opening secure checkout…');try{const {data:{session}}=await client.auth.getSession();if(!session?.access_token)throw new Error('Please log in again.');const r=await fetch('/api/create-checkout',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.url)throw new Error(d.error||'Unable to start checkout.');location.href=d.url}catch(e){msg(e.message||'Unable to start checkout.','error');if(b)b.disabled=false}}
  function showPaywall(){
    gate.innerHTML=`<div class="sha-card"><div class="sha-brand">SHAROVA LIFE OS</div><h1>Unlock your Life OS.</h1><p class="sha-sub">Your account is ready. Complete the one-time purchase to unlock your private workspace.</p><div class="sha-price">$47 <span style="font-size:12px;font-weight:700">one time</span></div><div class="sha-note"><strong>Secure checkout:</strong> payment is handled by Stripe. Your card details are not stored by Sharova.</div><div class="sha-form"><div id="shaMsg" class="sha-msg"></div><button id="shaBuy" class="sha-primary" type="button">Buy &amp; unlock Sharova</button><button id="shaLogout" class="sha-secondary" type="button">Log out</button></div></div>`;document.getElementById('shaBuy').onclick=checkout;document.getElementById('shaLogout').onclick=async()=>{await client.auth.signOut();location.reload()};
  }
  async function authorize(u){if(isOwner(u))return true;if(!u?.email_confirmed_at){msg('Please confirm your email before entering Sharova Life OS.','error');showResend(true);return false}if(!await active(u)){showPaywall();return false}return true}
  function unlock(u){gate.remove();document.body.classList.remove('sha-locked');window.SHAROVA_USER=u;const bar=document.createElement('div');bar.className='sha-user';bar.innerHTML=`<span>${u.email}</span><button>Log out</button>`;bar.querySelector('button').onclick=async()=>{await client.auth.signOut();localStorage.removeItem('sharova-life-os-v1');location.reload()};document.body.appendChild(bar);window.dispatchEvent(new CustomEvent('sharova-auth-ready',{detail:u}))}
  async function start(){const cfg=await fetch('/api/config',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Account service is temporarily unavailable.');return r.json()});paymentMode=cfg.paymentMode==='direct'?'direct':'direct';if(!window.supabase){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}if(!cfg.supabaseUrl||!cfg.supabaseAnonKey)throw new Error('Account service is not configured.');client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);window.SHAROVA_SUPABASE_CLIENT=client;const {data}=await client.auth.getSession();if(data.session&&await authorize(data.session.user))unlock(data.session.user)}
  document.getElementById('shaAuthForm').onsubmit=async e=>{e.preventDefault();const email=document.getElementById('shaEmail').value.trim(),password=document.getElementById('shaPassword').value,signup=!document.getElementById('shaSignInTab').classList.contains('active'),submit=document.getElementById('shaSubmit');if(submit)submit.disabled=true;try{if(signup){if(password!==document.getElementById('shaConfirm').value){msg('Passwords do not match.','error');return}const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:document.getElementById('shaName').value.trim()},emailRedirectTo:PRODUCTION_URL+'/'}});if(error)throw error;if(data.user&&!data.session){msg('Account created. Check your email to confirm your account, then return here and log in.','ok');showResend(true);return}if(data.session){if(await authorize(data.session.user))unlock(data.session.user)}}else{const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;if(await authorize(data.user))unlock(data.user)}}catch(x){console.error('Sharova auth error',x);msg(x?.message||'We could not complete that request. Please try again.','error')}finally{const current=document.getElementById('shaSubmit');if(current)current.disabled=false}};
  document.getElementById('shaResend').onclick=async()=>{const email=document.getElementById('shaEmail').value.trim();if(!email)return;const {error}=await client.auth.resend({type:'signup',email,options:{emailRedirectTo:PRODUCTION_URL+'/'}});msg(error?error.message:'Verification email sent again. Check your inbox.',error?'error':'ok')};
  document.getElementById('shaForgot').onclick=async()=>{const email=document.getElementById('shaEmail').value.trim();if(!email)return;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:PRODUCTION_URL+'/'});msg(error?error.message:'Password reset instructions sent to your email.',error?'error':'ok')};
  start().catch(e=>{console.error('Sharova startup error',e);msg(e.message||'Could not load the account service. Please refresh and try again.','error')});
})();
