/* Sharova Life OS — customer authentication + paid-access gate via Supabase. */
(function(){
  const SUPABASE_URL='https://ofodxwpukrgegtavahfm.supabase.co';
  const SUPABASE_KEY='sb_publishable_RvJAQ8p31BacTxANx3gltw_KRxlpoxe';
  const PRODUCTION_URL='https://sharova-life-os.vercel.app';
  const redirectUrl=PRODUCTION_URL+'/';

  const style=document.createElement('style');
  style.textContent=`#sharova-auth-gate{position:fixed;inset:0;z-index:99999;background:rgba(31,25,22,.97);display:flex;align-items:center;justify-content:center;padding:20px;font-family:inherit}#sharova-auth-gate *{box-sizing:border-box}.sha-card{width:min(430px,100%);background:#fffaf5;border-radius:24px;padding:30px;box-shadow:0 24px 80px rgba(0,0,0,.35);color:#29231f}.sha-brand{letter-spacing:.18em;font-size:12px;font-weight:800;margin-bottom:8px}.sha-card h1{margin:0 0 8px;font-size:30px}.sha-sub{margin:0 0 22px;color:#6d625a;line-height:1.5}.sha-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;background:#eee5de;padding:5px;border-radius:12px;margin-bottom:18px}.sha-tabs button{border:0;background:transparent;padding:10px;border-radius:9px;font-weight:700;cursor:pointer}.sha-tabs button.active{background:#fff}.sha-form{display:grid;gap:12px}.sha-form label{font-size:12px;font-weight:700}.sha-form input{width:100%;padding:13px 14px;border:1px solid #d8ccc2;border-radius:10px;background:#fff;font:inherit}.sha-primary{border:0;border-radius:10px;padding:13px 16px;background:#29231f;color:#fff;font-weight:800;cursor:pointer}.sha-primary:disabled{opacity:.6}.sha-secondary{border:1px solid #d8ccc2;border-radius:10px;padding:12px 16px;background:#fffaf5;color:#29231f;font-weight:800;cursor:pointer}.sha-link{border:0;background:none;color:#6b4f3d;font-weight:700;cursor:pointer;padding:4px}.sha-msg{min-height:20px;font-size:13px;color:#6d625a}.sha-msg.error{color:#a33}.sha-msg.ok{color:#276b42}.sha-hide{display:none!important}body.sha-locked{overflow:hidden}.sha-user{position:fixed;right:18px;top:82px;z-index:30;display:flex;gap:7px;align-items:center}.sha-user span,.sha-user button{background:#fffaf5;border:1px solid #d8ccc2;border-radius:999px;padding:8px 11px;font-size:11px}.sha-user button{cursor:pointer}.sha-price{font-size:28px;font-weight:900;margin:14px 0 4px}.sha-small{font-size:12px;color:#6d625a;line-height:1.5}`;
  document.head.appendChild(style);

  const gate=document.createElement('div');
  gate.id='sharova-auth-gate';
  gate.innerHTML=`<div class="sha-card"><div class="sha-brand">SHAROVA LIFE OS</div><h1>Your private Life OS.</h1><p class="sha-sub">Create your own account so your Sharova workspace belongs to you.</p><div class="sha-tabs"><button id="shaSignInTab" class="active">Log in</button><button id="shaSignUpTab">Create account</button></div><form id="shaAuthForm" class="sha-form"><div id="shaNameWrap" class="sha-hide"><label>Name</label><input id="shaName" autocomplete="name" placeholder="Your name"></div><div><label>Email</label><input id="shaEmail" type="email" autocomplete="email" required placeholder="you@example.com"></div><div><label>Password</label><input id="shaPassword" type="password" minlength="8" required placeholder="At least 8 characters"></div><div id="shaConfirmWrap" class="sha-hide"><label>Confirm password</label><input id="shaConfirm" type="password" minlength="8" placeholder="Repeat your password"></div><div id="shaMsg" class="sha-msg"></div><button id="shaSubmit" class="sha-primary" type="submit">Log in</button><button id="shaForgot" class="sha-link" type="button">Forgot password?</button><button id="shaResend" class="sha-link sha-hide" type="button">Resend verification email</button></form></div>`;
  document.body.appendChild(gate);document.body.classList.add('sha-locked');

  const msg=(t,c='')=>{const e=document.getElementById('shaMsg');if(e){e.textContent=t;e.className='sha-msg '+c}};
  const showResend=show=>document.getElementById('shaResend').classList.toggle('sha-hide',!show);
  const mode=signup=>{document.getElementById('shaSignInTab').classList.toggle('active',!signup);document.getElementById('shaSignUpTab').classList.toggle('active',signup);document.getElementById('shaNameWrap').classList.toggle('sha-hide',!signup);document.getElementById('shaConfirmWrap').classList.toggle('sha-hide',!signup);document.getElementById('shaForgot').classList.toggle('sha-hide',signup);showResend(false);document.getElementById('shaSubmit').textContent=signup?'Create my account':'Log in';msg('')};
  document.getElementById('shaSignInTab').onclick=()=>mode(false);
  document.getElementById('shaSignUpTab').onclick=()=>mode(true);

  let client;
  const verified=user=>!!user?.email_confirmed_at;
  async function requireVerified(user){if(verified(user))return true;await client.auth.signOut();msg('Please confirm your email before entering Sharova Life OS.','error');showResend(true);return false}
  async function hasActiveEntitlement(user){const {data,error}=await client.from('user_entitlements').select('status,expires_at').eq('user_id',user.id).maybeSingle();if(error){msg('We could not verify your purchase access. Please try again.','error');return false}if(!data||data.status!=='active')return false;if(data.expires_at&&new Date(data.expires_at).getTime()<=Date.now())return false;return true}
  async function startCheckout(){const {data,error}=await client.auth.getSession();if(error||!data.session)return msg('Please log in again before purchasing.','error');const button=document.getElementById('shaBuy');if(button)button.disabled=true;try{const response=await fetch('/api/create-checkout',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`}});const result=await response.json();if(!response.ok||!result.url)throw new Error(result.error||'Unable to start checkout.');location.href=result.url}catch(err){msg(err.message||'Unable to start checkout.','error');if(button)button.disabled=false}}
  function showPaywall(){gate.innerHTML=`<div class="sha-card"><div class="sha-brand">SHAROVA LIFE OS</div><h1>Unlock your Life OS.</h1><p class="sha-sub">Your email is verified. Purchase lifetime access to unlock your private Sharova workspace on this account.</p><div class="sha-price">$47</div><div class="sha-small">One-time payment · Lifetime access</div><div style="height:14px"></div><button id="shaBuy" class="sha-primary" type="button">Buy Sharova Life OS</button><div style="height:8px"></div><button id="shaLogoutPaywall" class="sha-secondary" type="button">Log out</button><div id="shaMsg" class="sha-msg" style="margin-top:12px"></div></div>`;document.getElementById('shaBuy').onclick=startCheckout;document.getElementById('shaLogoutPaywall').onclick=async()=>{await client.auth.signOut();localStorage.removeItem('sharova-life-os-v1');location.reload()}}
  async function authorize(user){if(!await requireVerified(user))return false;if(!await hasActiveEntitlement(user)){showPaywall();return false}return true}
  async function start(){if(!window.supabase){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.SHAROVA_SUPABASE_CLIENT=client;const {data}=await client.auth.getSession();if(data.session&&await authorize(data.session.user))unlock(data.session.user)}
  function unlock(user){gate.remove();document.body.classList.remove('sha-locked');window.SHAROVA_USER=user;const bar=document.createElement('div');bar.className='sha-user';bar.innerHTML=`<span>${user.email}</span><button>Log out</button>`;bar.querySelector('button').onclick=async()=>{await client.auth.signOut();localStorage.removeItem('sharova-life-os-v1');location.reload()};document.body.appendChild(bar);window.dispatchEvent(new CustomEvent('sharova-auth-ready',{detail:user}))}

  document.getElementById('shaAuthForm').onsubmit=async e=>{e.preventDefault();if(!client)return;const email=document.getElementById('shaEmail').value.trim(),password=document.getElementById('shaPassword').value,signup=document.getElementById('shaSignUpTab').classList.contains('active');document.getElementById('shaSubmit').disabled=true;try{if(signup){const confirm=document.getElementById('shaConfirm').value;if(password!==confirm){msg('Passwords do not match.','error');return}const name=document.getElementById('shaName').value.trim();const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:redirectUrl}});if(error)throw error;if(data.session){if(await authorize(data.session.user))unlock(data.session.user)}else{msg('Account created. Check your email to confirm it, then return here to log in.','ok');showResend(true)}}else{const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;if(await authorize(data.user))unlock(data.user)}}catch(err){msg(err.message||'Unable to complete that request.','error')}finally{document.getElementById('shaSubmit').disabled=false}};

  document.getElementById('shaResend').onclick=async()=>{const email=document.getElementById('shaEmail').value.trim();if(!email)return;const {error}=await client.auth.resend({type:'signup',email,options:{emailRedirectTo:redirectUrl}});msg(error?error.message:'Verification email sent again. Check your inbox.',''+(error?'error':'ok'))};
  document.getElementById('shaForgot').onclick=async()=>{const email=document.getElementById('shaEmail').value.trim();if(!email)return;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:redirectUrl});msg(error?error.message:'Password reset instructions sent to your email.',error?'error':'ok')};
  start().catch(()=>msg('Could not load the account service.','error'));
})();
