/* Sharova Life OS — customer authentication + Creative Market access gate. */
(function(){
  const SUPABASE_URL='https://ofodxwpukrgegtavahfm.supabase.co';
  // Public browser key only. Never put a Supabase service-role key here.
  const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mb2R4d3B1a3JnZWd0YXZhaGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxMDAwOTMsImV4cCI6MjEwNDY3NjA5M30.mziHndjCgOwE3oU_iQmceYehp5uWZdS1tQs-YSTuvhI';
  const PRODUCTION_URL='https://sharova-life-os.vercel.app';
  const OWNER_EMAIL='sharonvugutsa12@gmail.com';
  const TESTER_EMAIL='askahnyaboke1998@gmail.com';
  const redirectUrl=PRODUCTION_URL+'/';

  const style=document.createElement('style');
  style.textContent=`#sharova-auth-gate{position:fixed;inset:0;z-index:99999;background:rgba(31,25,22,.97);display:flex;align-items:center;justify-content:center;padding:20px;font-family:inherit}#sharova-auth-gate *{box-sizing:border-box}.sha-card{width:min(440px,100%);background:#fffaf5;border-radius:24px;padding:30px;box-shadow:0 24px 80px rgba(0,0,0,.35);color:#29231f}.sha-brand{letter-spacing:.18em;font-size:12px;font-weight:800;margin-bottom:8px}.sha-card h1{margin:0 0 8px;font-size:30px}.sha-sub{margin:0 0 22px;color:#6d625a;line-height:1.5}.sha-tabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;background:#eee5de;padding:5px;border-radius:12px;margin-bottom:18px}.sha-tabs button{border:0;background:transparent;padding:10px;border-radius:9px;font-weight:700;cursor:pointer}.sha-tabs button.active{background:#fff}.sha-form{display:grid;gap:12px}.sha-form label{font-size:12px;font-weight:700}.sha-form input{width:100%;padding:13px 14px;border:1px solid #d8ccc2;border-radius:10px;background:#fff;font:inherit}.sha-primary{border:0;border-radius:10px;padding:13px 16px;background:#29231f;color:#fff;font-weight:800;cursor:pointer}.sha-primary:disabled{opacity:.6}.sha-secondary{border:1px solid #d8ccc2;border-radius:10px;padding:12px 16px;background:#fffaf5;color:#29231f;font-weight:800;cursor:pointer}.sha-link{border:0;background:none;color:#6b4f3d;font-weight:700;cursor:pointer;padding:4px}.sha-msg{min-height:20px;font-size:13px;color:#6d625a}.sha-msg.error{color:#a33}.sha-msg.ok{color:#276b42}.sha-hide{display:none!important}body.sha-locked{overflow:hidden}.sha-user{position:fixed;right:18px;top:82px;z-index:30;display:flex;gap:7px;align-items:center}.sha-user span,.sha-user button{background:#fffaf5;border:1px solid #d8ccc2;border-radius:999px;padding:8px 11px;font-size:11px}.sha-user button{cursor:pointer}.sha-price{font-size:28px;font-weight:900;margin:14px 0 4px}.sha-small{font-size:12px;color:#6d625a;line-height:1.5}.sha-note{padding:12px 14px;border-radius:12px;background:#f2e9e2;color:#5f554e;font-size:12px;line-height:1.5;margin:14px 0}.sha-code{letter-spacing:.08em;text-transform:uppercase}`;
  document.head.appendChild(style);

  const gate=document.createElement('div');
  gate.id='sharova-auth-gate';
  gate.innerHTML=`<div class="sha-card"><div class="sha-brand">SHAROVA LIFE OS</div><h1>Your private Life OS.</h1><p class="sha-sub">Create an account to keep your Sharova workspace private and synced across your devices.</p><div class="sha-tabs"><button id="shaSignInTab" class="active">Log in</button><button id="shaSignUpTab">Create account</button></div><form id="shaAuthForm" class="sha-form"><div id="shaNameWrap" class="sha-hide"><label>Name</label><input id="shaName" autocomplete="name" placeholder="Your name"></div><div><label>Email</label><input id="shaEmail" type="email" autocomplete="email" required placeholder="you@example.com"></div><div><label>Password</label><input id="shaPassword" type="password" minlength="8" required placeholder="At least 8 characters"></div><div id="shaConfirmWrap" class="sha-hide"><label>Confirm password</label><input id="shaConfirm" type="password" minlength="8" placeholder="Repeat your password"></div><div id="shaMsg" class="sha-msg"></div><button id="shaSubmit" class="sha-primary" type="submit">Log in</button><button id="shaForgot" class="sha-link" type="button">Forgot password?</button><button id="shaResend" class="sha-link sha-hide" type="button">Resend verification email</button></form></div>`;
  document.body.appendChild(gate);document.body.classList.add('sha-locked');

  const msg=(t,c='')=>{const e=document.getElementById('shaMsg');if(e){e.textContent=t;e.className='sha-msg '+c}};
  const showResend=show=>document.getElementById('shaResend').classList.toggle('sha-hide',!show);
  const mode=signup=>{document.getElementById('shaSignInTab').classList.toggle('active',!signup);document.getElementById('shaSignUpTab').classList.toggle('active',signup);document.getElementById('shaNameWrap').classList.toggle('sha-hide',!signup);document.getElementById('shaConfirmWrap').classList.toggle('sha-hide',!signup);document.getElementById('shaForgot').classList.toggle('sha-hide',signup);showResend(false);document.getElementById('shaSubmit').textContent=signup?'Create my account':'Log in';msg('')};
  document.getElementById('shaSignInTab').onclick=()=>mode(false);
  document.getElementById('shaSignUpTab').onclick=()=>mode(true);

  let client;
  const isOwner=user=>String(user?.email||'').trim().toLowerCase()===OWNER_EMAIL.toLowerCase();
  const isTester=user=>String(user?.email||'').trim().toLowerCase()===TESTER_EMAIL.toLowerCase();
  const verified=user=>!!user?.email_confirmed_at;
  async function requireVerified(user){if(verified(user))return true;await client.auth.signOut();msg('Please confirm your email before entering Sharova Life OS.','error');showResend(true);return false}
  async function hasActiveEntitlement(user){const {data,error}=await client.from('user_entitlements').select('status,expires_at').eq('user_id',user.id).maybeSingle();if(error){msg('We could not verify your access. Please try again.','error');return false}if(!data||data.status!=='active')return false;if(data.expires_at&&new Date(data.expires_at).getTime()<=Date.now())return false;return true}
  async function claimCreativeMarketCode(code){const {data,error}=await client.rpc('claim_sharova_activation',{p_code:code});if(error)throw error;return data?.success===true}
  function showPaywall(){
    gate.innerHTML=`<div class="sha-card"><div class="sha-brand">SHAROVA LIFE OS</div><h1>Welcome to your Life OS.</h1><p class="sha-sub">Your account is ready. If you bought Sharova Life OS on Creative Market, you already paid for your access.</p><div class="sha-note"><strong>Important:</strong> You do not pay $47 again inside Sharova. Enter the activation code included with your Creative Market purchase.</div><form id="shaActivateForm" class="sha-form"><div><label>Creative Market activation code</label><input id="shaCode" class="sha-code" autocomplete="off" placeholder="Enter your activation code" required></div><div id="shaMsg" class="sha-msg"></div><button id="shaActivate" class="sha-primary" type="submit">Unlock my Life OS</button><button id="shaLogoutPaywall" class="sha-secondary" type="button">Log out</button></form></div>`;
    document.getElementById('shaActivateForm').onsubmit=async e=>{e.preventDefault();const button=document.getElementById('shaActivate');const code=document.getElementById('shaCode').value.trim();button.disabled=true;msg('Checking your purchase…');try{if(!code)throw new Error('Enter the activation code from your Creative Market purchase.');const ok=await claimCreativeMarketCode(code);if(!ok)throw new Error('That activation code could not be verified.');msg('Access unlocked. Opening your Life OS…','ok');setTimeout(()=>location.reload(),500)}catch(err){msg(err.message||'Unable to activate your purchase.','error');button.disabled=false}};
    document.getElementById('shaLogoutPaywall').onclick=async()=>{await client.auth.signOut();localStorage.removeItem('sharova-life-os-v1');location.reload()};
  }
  async function authorize(user){if(isOwner(user)||isTester(user))return true;if(!await requireVerified(user))return false;if(!await hasActiveEntitlement(user)){showPaywall();return false}return true}
  function unlock(user){gate.remove();document.body.classList.remove('sha-locked');window.SHAROVA_USER=user;const bar=document.createElement('div');bar.className='sha-user';bar.innerHTML=`<span>${user.email}</span><button>Log out</button>`;bar.querySelector('button').onclick=async()=>{await client.auth.signOut();localStorage.removeItem('sharova-life-os-v1');location.reload()};document.body.appendChild(bar);window.dispatchEvent(new CustomEvent('sharova-auth-ready',{detail:user}))}
  async function start(){if(!window.supabase){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.SHAROVA_SUPABASE_CLIENT=client;const {data}=await client.auth.getSession();if(data.session&&await authorize(data.session.user))unlock(data.session.user)}

  document.getElementById('shaAuthForm').onsubmit=async e=>{e.preventDefault();if(!client)return;const email=document.getElementById('shaEmail').value.trim(),password=document.getElementById('shaPassword').value,signup=document.getElementById('shaSignInTab').classList.contains('active')===false;document.getElementById('shaSubmit').disabled=true;try{if(signup){const confirm=document.getElementById('shaConfirm').value;if(password!==confirm){msg('Passwords do not match.','error');return}const name=document.getElementById('shaName').value.trim();const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:redirectUrl}});if(error)throw error;if(data.session){if(await authorize(data.session.user))unlock(data.session.user)}else{msg('Account created. Check your email to confirm it, then return here to log in.','ok');showResend(true)}}else{const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;if(await authorize(data.user))unlock(data.user)}}catch(err){msg(err.message||'Unable to complete that request.','error')}finally{document.getElementById('shaSubmit').disabled=false}};
  document.getElementById('shaResend').onclick=async()=>{const email=document.getElementById('shaEmail').value.trim();if(!email)return;const {error}=await client.auth.resend({type:'signup',email,options:{emailRedirectTo:redirectUrl}});msg(error?error.message:'Verification email sent again. Check your inbox.',error?'error':'ok')};
  document.getElementById('shaForgot').onclick=async()=>{const email=document.getElementById('shaEmail').value.trim();if(!email)return;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:redirectUrl});msg(error?error.message:'Password reset instructions sent to your email.',error?'error':'ok')};
  start().catch(()=>msg('Could not load the account service.','error'));
})();
